// <auto-generated />
namespace Web_Technology.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreatetableProductandCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatetableProductandCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202204091159361_Create table Product and Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
